// Patrimonio / Inventario (NTEi only)
const patrimonio = (function(){
  async function init(){ renderInventario(); }
  async function renderInventario(){ const box = document.getElementById('inventario-lista-pat'); if(!box) return; const arr = JSON.parse(localStorage.getItem('inventario')||'[]'); if(arr.length===0){ box.innerHTML='<div class="info-box">Nenhum item cadastrado.</div>'; return; } box.innerHTML=''; arr.forEach(i=>{ const div = document.createElement('div'); div.className='res-card-agenda'; div.innerHTML=`<b>${i.nome||i.modelo||i.tag}</b> <div style="font-size:12px; color:var(--text-muted)">Status: ${i.status||'—'} • Local: ${i.local||'—'}</div><div style="margin-top:6px; display:flex; gap:6px"><button class="btn" style="width:auto; padding:6px; background:var(--prof)" onclick="patrimonio.editar('${i.id}')">Editar</button><button class="btn" style="width:auto; padding:6px; background:rgba(235,77,75,0.12)" onclick="patrimonio.remover('${i.id}')">Excluir</button></div>`; box.appendChild(div); }); document.getElementById('inv-total').textContent = arr.length; document.getElementById('inv-disp').textContent = arr.filter(x=> x.status==='Disponível').length; document.getElementById('inv-uso').textContent = arr.filter(x=> x.status==='Em Uso').length; document.getElementById('inv-manut').textContent = arr.filter(x=> x.status==='Manutenção').length; }
  async function adicionar(item){ const allowed = await perm.canAction('patrimonio:manage'); if(!allowed) return alert('Permissão negada'); const arr = JSON.parse(localStorage.getItem('inventario')||'[]'); arr.push(item); localStorage.setItem('inventario', JSON.stringify(arr)); await audit.log('inventario_add', auth.getCurrentUser()?auth.getCurrentUser().prontuario:'unknown', item.id, item); renderInventario(); }
  function editar(id){ alert('Editar inventário: '+id+' (funcionalidade rápida a implementar)'); }
  async function remover(id){ const allowed = await perm.canAction('patrimonio:manage'); if(!allowed) return alert('Permissão negada'); let arr = JSON.parse(localStorage.getItem('inventario')||'[]'); arr = arr.filter(x=> x.id !== id); localStorage.setItem('inventario', JSON.stringify(arr)); await audit.log('inventario_delete', auth.getCurrentUser()?auth.getCurrentUser().prontuario:'unknown', id, {}); renderInventario(); }
  return { init, renderInventario, adicionar, editar, remover };
})();
window.patrimonio = patrimonio;
